package com.ispw.model.enums;

public enum TipoOperazione {
    
    REGISTRAZIONE_ACCOUNT,
    ACCOUNT_ATTIVATO,
    ACCESSO_ESEGUITO,
    ACCESSO_FALLITO,
    PASSWORD_RECUPERO_RICHIESTA,
    PASSWORD_AGGIORNAMENTO,
    ACCOUNT_PENALIZZAZIONE,
    AGGIORNAMENTO_DATI_PERSONALI,
    LOGOUT_ESEGUITO

}
