package com.ispw.model.enums;

public enum TipoOperazione {
    
    REGISTRAZIONE_CREAZIONE,
    ATTIVAZIONE_SUCCESSO,
    LOGIN_SUCCESSO,
    LOGIN_FALLITO,
    PASSWORD_RECUPERO_RICHIESTA,
    PASSWORD_AGGIORNAMENTO,
    ACCOUNT_PENALIZZAZIONE,
    AGGIORNAMENTO_DATI_PERSONALI,
    LOGOUT

}
